name: Deploy Hexo to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: NPM config for legacy deps
        run: |
          npm config set legacy-peer-deps true
          npm config set fund false
          npm config set audit false

      - name: Install dependencies (root)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Install dependencies (theme)
        run: |
          cd themes/hexo-theme-aurora
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build site
        run: |
          npm run clean
          npx hexo generate -c _config.yml,_config.hexo-theme-aurora.yml,_config.gh.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4